### ISSUE TITLE
Basic usecase doesn't work or is undocumented

### ISSUE THREAD

**Issue by laurivosandi** [howardjohn/kubectl-grep#3]
After spending good 15min+ trying to get it to work I was unable to successfully search secrets and I gave up using `kubectl-grep`.

Please document what is the equivalent of:

```
kubectl get secrets -o=jsonpath="{.items[*]}"  | jq '.data | map_values(@base64d)' | grep foobar
```

I tried following variations but none actually make the relevant entry to pop up:

```
kubectl get secrets -o=json    | kubectl grep foobar
kubectl get secrets -o=jsonpath="{.items[*]}"  | kubectl grep -nN -r foobar
kubectl get secrets -o=json | kubectl grep -nN -r foobar
kubectl get secrets -o=json -w  | kubectl grep -wnN -r foobar
```

**Comment by howardjohn** [comment]
`kubectl get secrets -oyaml| kubectl grep -d -r foobar` should do it. it would output the full secret yaml not just the .data section, so you would also want to pipe it to jq (converting from yaml to json before or using a similar tool with yaml support) to extract just the data value if you want that.
